// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbsaFEZtqnQ26i5p9IAX-yYiw_HudsMIk',
    appId: '1:974286719427:web:1fe5fe9678009814f51576',
    messagingSenderId: '974286719427',
    projectId: 'flix-id-d40e3',
    authDomain: 'flix-id-d40e3.firebaseapp.com',
    storageBucket: 'flix-id-d40e3.appspot.com',
    measurementId: 'G-PSSS8TCNBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhThA9UOehrZEb-u9Ch_5S_rWnx4SmD2Q',
    appId: '1:974286719427:android:ba1cf09f3a2855c1f51576',
    messagingSenderId: '974286719427',
    projectId: 'flix-id-d40e3',
    storageBucket: 'flix-id-d40e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_MPP4TbR8p2v3Pdx-KQDjAWgMUYCdTY',
    appId: '1:974286719427:ios:e4e1c08673bcfd5bf51576',
    messagingSenderId: '974286719427',
    projectId: 'flix-id-d40e3',
    storageBucket: 'flix-id-d40e3.appspot.com',
    iosBundleId: 'com.example.flixId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_MPP4TbR8p2v3Pdx-KQDjAWgMUYCdTY',
    appId: '1:974286719427:ios:370b8a94a66da8e3f51576',
    messagingSenderId: '974286719427',
    projectId: 'flix-id-d40e3',
    storageBucket: 'flix-id-d40e3.appspot.com',
    iosBundleId: 'com.example.flixId.RunnerTests',
  );
}
